### PR TITLE
The possibility of choosing more than one item, not just one and other changes:

### PR DESCRIPTION
**Pull request by AhmedSama**
- ###  The possibility of choosing more than one item, not just one in visiting.
- ### fixing the bug where u cancel the visiting and the verified visit for that visiting in (visit goal doctype) not effected.
- ### making the unpaid invoices button in collecting doctype will not get the draft invoice.

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by osama1998H** [comment]
great work bro

**Review by osama1998H — COMMENTED** [review]
your code isn't very clean and has a lot of empty lines and spaces can you reformat your code and make it nicer

**Comment by osama1998H** [comment]
i accept it you need to make the changes on the new version

**Comment by AhmedSama** [comment]
i will refactor the code of course

**Pull request merged**
